package com.yingfa.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBorrowReturn<M extends BaseBorrowReturn<M>> extends Model<M> implements IBean {

	/**
	 * 标识
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 类型
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 学生ID
	 */
	public M setStudentId(java.lang.Integer studentId) {
		set("student_id", studentId);
		return (M)this;
	}
	
	/**
	 * 学生ID
	 */
	public java.lang.Integer getStudentId() {
		return getInt("student_id");
	}

	/**
	 * 图书Id
	 */
	public M setBookId(java.lang.Integer bookId) {
		set("book_id", bookId);
		return (M)this;
	}
	
	/**
	 * 图书Id
	 */
	public java.lang.Integer getBookId() {
		return getInt("book_id");
	}

	/**
	 * 用户ID
	 */
	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	/**
	 * 用户ID
	 */
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
