package com.yingfa.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBook<M extends BaseBook<M>> extends Model<M> implements IBean {

	/**
	 * 标识
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 标识
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 条形码
	 */
	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	/**
	 * 条形码
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}

	/**
	 * 图片
	 */
	public M setImage(java.lang.String image) {
		set("image", image);
		return (M)this;
	}
	
	/**
	 * 图片
	 */
	public java.lang.String getImage() {
		return getStr("image");
	}

	/**
	 * 在馆数量
	 */
	public M setCurrentCount(java.lang.Integer currentCount) {
		set("current_count", currentCount);
		return (M)this;
	}
	
	/**
	 * 在馆数量
	 */
	public java.lang.Integer getCurrentCount() {
		return getInt("current_count");
	}

	/**
	 * 借出数量
	 */
	public M setOutCount(java.lang.Integer outCount) {
		set("out_count", outCount);
		return (M)this;
	}
	
	/**
	 * 借出数量
	 */
	public java.lang.Integer getOutCount() {
		return getInt("out_count");
	}

	/**
	 * 类型id
	 */
	public M setCategoryId(java.lang.Integer categoryId) {
		set("category_id", categoryId);
		return (M)this;
	}
	
	/**
	 * 类型id
	 */
	public java.lang.Integer getCategoryId() {
		return getInt("category_id");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

}
