package com.yingfa.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("book", "id", Book.class);
		arp.addMapping("book_category", "id", BookCategory.class);
		arp.addMapping("borrow_return", "id", BorrowReturn.class);
		arp.addMapping("student", "id", Student.class);
		arp.addMapping("user", "id", User.class);
	}
}

