package com.yingfa.common.model;

import com.yingfa.common.model.base.BaseBookCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookCategory extends BaseBookCategory<BookCategory> {
	public static final BookCategory dao = new BookCategory().dao();
}
