package com.yingfa.common.model;

import com.yingfa.common.model.base.BaseBorrowReturn;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BorrowReturn extends BaseBorrowReturn<BorrowReturn> {
	public static final BorrowReturn dao = new BorrowReturn().dao();
}
